#### ***Ví dụ 3.2.2***  Minh họa cách xác định và truy cập kiểu dữ liệu (dtype) của các mảng NumPy ndarray khi chúng được khởi tạo với các kiểu dữ liệu khác nhau.

In [1]:
import numpy as np

In [2]:
import numpy as np
arr_int=np.array([1,2,3,4],dtype=np.int32)
arr_int.dtype 

dtype('int32')

In [2]:
import numpy as np
arr_float=np.array([1,2,3,4],dtype=np.float64)
arr_float.dtype 

dtype('float64')

In [1]:
import numpy as np

arr_string = np.array(['apple', 'banana', 'orange'], dtype=np.str_)
print(arr_string)
print(arr_string.dtype)

['apple' 'banana' 'orange']
<U6


In [3]:
import numpy as np
arr_bool = np.array([True, False,True], dtype=np.bool_)
arr_bool.dtype

dtype('bool')

#### ***Chuyển đổi kiểu dữ liệu***

In [4]:
import numpy as np

arr = np.array([1.5, 2.7, 3.2])    
arr_int = arr.astype(np.int32)     
print(arr_int, arr_int.dtype)      


[1 2 3] int32


In [11]:
import numpy as np
my_list = [1, 2, 3, 4, 5]
arr_1 = np.array(my_list)
print(arr_1, arr_1.dtype)

[1 2 3 4 5] int64


In [13]:
import numpy as np
my_list = [1, 2, 3, 4, 5]
arr_2 = np.array(my_list, dtype=float)
print(arr_2,arr_2.dtype)

[1. 2. 3. 4. 5.] float64


In [15]:
import numpy as np
my_tuple = (1, 2, 3, 4, 5)
arr_3 = np.array(my_tuple)
print(arr_3, arr_3.dtype)

[1 2 3 4 5] int64


In [16]:
import numpy as np
arr_4=np.array([(1,2,3), (4,5,6)])
print(arr_4, arr_4.dtype)

[[1 2 3]
 [4 5 6]] int64


#### ***d. Một số hàm tạo mảng numpy array***

***1. Hàm zeros()***

In [25]:
import numpy as np
#Tạo mảng có 5 phần tử là số nguyên nhận giá trị 0
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

***2. Hàm ones()***

In [18]:
import numpy as np
# Tạo mảng kích thước 3x3 các số thực có giá trị = 1
np.ones((3,3),dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

***3. Hàm full()***

In [26]:
import numpy as np
# Tạo mảng kích thước 5x5 các số thực có giá trị = 100
np.full((5,5),100,dtype=float)

array([[100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.]])

***4. Hàm np.arange()***

**Ví dụ minh họa hàm np.arrange().**

In [27]:
import numpy as np
# Tạo mảng các số nguyên từ 0 đến 9
arr_1 = np.arange(10)
print(arr_1)

[0 1 2 3 4 5 6 7 8 9]


In [28]:
import  numpy as np
# Tạo mảng chứa các số từ 5 đến 14 với bước nhảy là 2
arr_2 = np.arange(5, 15, 2)
print(arr_2)

[ 5  7  9 11 13]


In [ ]:
import numpy as np
# Tạo mảng chứa các số từ 0 đến 1 với bước nhảy là 0.1 và kiểu dữ liệu là float.
arr_3 = np.arange(0, 1, 0.1, dtype=float)
print(arr_3)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


***5. Hàm numpy.linspace()***

**Ví dụ. minh họa hàm np.linspace()**

In [31]:
import numpy as np
# Tạo mảng chứa 5 giá trị từ 0 đến 10 (gồm giá trị kết thúc)
arr_1 = np.linspace(0, 10, 5)
print(arr_1)

[ 0.   2.5  5.   7.5 10. ]


In [32]:
# Tạo mảng chứa 10 giá trị từ 0 đến 1 (không chứa giá trị # kết thúc)
arr_2 = np.linspace(0, 1, 10, endpoint=False)
print(arr_2)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [33]:
# Tạo mảng chứa 100 giá trị từ 1 đến 10 và trả về kích thước bước.
arr_3, step = np.linspace(1, 10, 100, retstep=True)
print(arr_3)
print("Step size:", step)

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

**Ví dụ. Sử dụng hàm numpy.linspace() để tạo một mảng có 5 phần tử từ 0 đến 10 với kiểu dữ liệu là float.**

In [34]:
import numpy as np
# Tạo mảng gồm 5 phần tử từ 0 đến 10 với kiểu dữ liệu là float
arr_4 = np.linspace(0, 10, num=5, dtype=float)
print(arr_4)
print(arr_4.dtype)

[ 0.   2.5  5.   7.5 10. ]
float64


***6. Hàm np.random.random()***

In [35]:
import numpy as np
# Tạo môt mảng 1 chiều gồm 5 giá trị ngẫu nhiên từ phân phối đều
#trong khoảng từ 0 đến 1
arr_5 = np.random.random(5)
print(arr_5)

[0.51381063 0.40622749 0.23681754 0.48625004 0.04425183]


***7.Hàm np.random.normal()***

**Ví dụ. hãy tạo ra một mảng 100 giá trị ngẫu nhiên từ phân phối chuẩn với trung bình 0 và độ lệch chuẩn 1.**

In [36]:
import numpy as np
# Tạo môt mảng 100 giá trị ngẫu nhiên từ phân phối chuẩn với trung bình 0 và độ lệch chuẩn là 1.
arr_6 = np.random.normal(loc=0.0, scale=1.0, size=100)
print(arr_6)

[ 0.02092447 -0.48366332 -0.2268621   0.3036935  -1.08648495  0.15670434
 -0.68318071 -1.10579002 -0.05029207  0.18668675  1.3605717  -2.21422125
  0.31894259 -0.01453304  0.15802258 -1.40338166 -1.75832795  0.26087522
 -0.68501895 -0.83939161 -1.15356907  0.12112882 -0.40262601 -0.66203866
  1.11698769 -0.87929515 -0.69906651  1.13117561 -0.65483884 -1.57558286
  1.58094422 -0.42779906  0.13978189 -0.39036368  1.20280343 -1.79993203
 -0.54325285 -0.65953765  0.10893688 -1.52173981 -1.42959827  0.74571978
  0.92812539 -1.56816913 -0.01596553 -0.46517148 -0.8019837  -0.42970539
  0.86641257  1.07971813  1.8996953  -0.62231201  0.63276694 -0.4141936
  0.22966361  0.60902956  0.19939022  0.33034799  0.37347144 -0.96685592
 -1.47109017 -0.16727487 -1.04648213  0.52169946 -0.23888852 -0.44958347
  0.87276622 -0.80478894 -1.21114456 -0.24923172 -0.36420593 -0.60904556
 -0.61896272  0.06598727  0.46985542 -0.69424596  0.67598486 -1.51000086
  1.65783348  0.0601746  -0.01724405  0.34643645 -1.

***8. Hàm np.random.randint()***

**Ví dụ. Tạo một mảng gồm 3x3 các số nguyên ngẫu nhiên từ 0 đến 9.**|

In [37]:
import numpy as np
# Tạo mảng 2 chiều 3x3 gồm các số nguyên ngẫu nhiên từ 0 9
arr_7 = np.random.randint(0,10,(3,3))
print(arr_7)

[[8 6 3]
 [7 7 3]
 [1 5 3]]


***9. Hàm.eye()***

**Ví dụ. Tạo một ma trận đơn vị 3x3.**

In [38]:
import numpy as np
# Tạo mảng 2 chiều 3x3
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

***10. Hàm empty()***

In [39]:
import numpy as np
# Tạo mảng rỗng gồm 5 phần tử, giá trị của 5 phần tử này có thể là bất kỳ giá trị
# nào đã lưu trong bộ nhớ trước đó.
np.empty(5)

array([0.51381063, 0.40622749, 0.23681754, 0.48625004, 0.04425183])

##### ***3.3. XỬ LÝ DỮ LIỆU TRÊN MẢNG CƠ BẢN VỚI NUMPY***

In [10]:
!python -m pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [11]:
!python -m pip install --upgrade numpy

Defaulting to user installation because normal site-packages is not writeable


***3.3.1. Thuộc tính cơ bản của mảng Numpy***

In [12]:
import numpy as np

In [13]:
arr=np.array([[1,2,3],[4,5,6]])

In [14]:
print("Số chiều của mảng là:",arr.ndim)
print("Kích thước của mảng là:",arr.shape)
print("Tổng số phần tử trong mảng là:", arr.size)
print("Kiểu dữ liệu của các phần tử trong mảng là:", arr.dtype)
print("Kích thước theo (byte) của mỗi phần tử trong mảng là:", arr.itemsize)
print("Tổng kích thước theo (byte) của mảng là: ", arr.nbytes)

Số chiều của mảng là: 2
Kích thước của mảng là: (2, 3)
Tổng số phần tử trong mảng là: 6
Kiểu dữ liệu của các phần tử trong mảng là: int64
Kích thước theo (byte) của mỗi phần tử trong mảng là: 8
Tổng kích thước theo (byte) của mảng là:  48


***Ví dụ 3.3.1.2. Cho ma trận a như sau : Hãy tính tổng các phần tử của A, tổng theo các cột (axit 0), tổng theo các hàng (axis 1) của mảng a.***

In [15]:
import numpy as np
arr_a = np.array([[1,2,3,4],
[5,6,7,8],
[9,10,11,12]])
#dùng hàm np.sum() và không có 'axis'
np.sum(arr_a)

np.int64(78)

In [16]:
#Dùng hàm np.sum() với 'axis =0'
np.sum(arr_a, axis=0)

array([15, 18, 21, 24])

In [17]:
#Dùng hàm np.sum với 'axis=1
np.sum(arr_a, axis=1)

array([10, 26, 42])

***3.3.2. Truy cập vào các phần tử trong mảng Numpy***

**a. Array indexing**

*Ví dụ 3.3.2.1.*

In [18]:
import numpy as np
A=np.array([1, 2, 3, 4, 5])
A[0] #Phần tử ở vị trí đầu tiên của mảng A

np.int64(1)

In [19]:
A[4] #Phần tử ở vị trí thứ năm của mảng A

np.int64(5)

In [20]:
A[-1] #Phần tử ở vị trí cuối cùng của mảng A

np.int64(5)

In [21]:
A[-2] #Phần tử ở vị trí thứ hai tử cuối mảng 

np.int64(4)

*Ví dụ 3.3.2.2.*

In [22]:
import numpy as np
B=np.array([[1,2,3],[4,5,6],[7,8,9]])
B[1,2] #Phần tử ở dòng 1, cột 2 của mảng B

np.int64(6)

In [23]:
B[0,0] #Phần tử ở dòng 0, cột 0 của mảng B

np.int64(1)

In [24]:
B[2,0] #Phần tử ở dòng 2, cột 0 của mảng B

np.int64(7)

In [25]:
B[2,-1] #Phần tử ở dòng 2, cột 2 

np.int64(9)

In [26]:
B[0,0]=0
np.array(B)

array([[0, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr_int_32 = np.array([1, 2, 3, 4, 5], dtype=np.int32)
arr_int_32

array([1, 2, 3, 4, 5], dtype=int32)

In [27]:
arr_str = np.array(["A", "B", "C"], dtype=np.str_)
arr_str

array(['A', 'B', 'C'], dtype='<U1')

In [29]:
arr_str = np.array(['Abc', 'Ba', 'C1234'], dtype=np.str_)
arr_str

array(['Abc', 'Ba', 'C1234'], dtype='<U5')

In [30]:
arr_boolean = np.array([True, False], dtype = np.bool_)
arr_boolean

array([ True, False])

In [31]:
arr_boolean.dtype

dtype('bool')

In [35]:
lst = [1, 2, 3, 4, 5]
arr_lst = np.array(lst, dtype = np.float64)
arr_lst

array([1., 2., 3., 4., 5.])

In [36]:
tpl = (1, 2, 3, 4, 5)
arr_tpl = np.array(tpl, dtype=np.int32)
arr_tpl

array([1, 2, 3, 4, 5], dtype=int32)

In [37]:
maxtr = [(1,2,3),
         (4,5,6)]
arr_matr = np.array(maxtr)
arr_matr

array([[1, 2, 3],
       [4, 5, 6]])

Hàm np.zero
Tạo một mảng array chỉ có số 0

In [38]:
array_zero = np.zeros(10, dtype=np.int32)
array_zero

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [39]:
array_one = np.ones(10, dtype = np.int32)
array_one

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [42]:
array_zero_ = np.zeros((4,4), dtype=np.int32)
array_zero_

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [44]:
array_one_ = np.ones((4,4), dtype=np.int32)
array_one_

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

Hàm np.full

Tạo và lấp đầy mảng bằng một giá trị bất kì

In [51]:
arr_full = np.full((3,2), '100', dtype = np.float64)
arr_full

array([[100., 100.],
       [100., 100.],
       [100., 100.]])

Hàm np.arange

Khởi tạo một array chứa các giá trị liên tiếp trong một khoảng đã chọn

range(1, 100,2)

In [52]:
arr_1 = np.arange(20)
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [53]:
arr_2 = np.arange(5,20,2)
arr_2

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [54]:
arr_3 = np.arange(0,1,0.1,dtype = np.float32)
arr_3

array([0.        , 0.1       , 0.2       , 0.3       , 0.4       ,
       0.5       , 0.6       , 0.7       , 0.8       , 0.90000004],
      dtype=float32)

Hàm np.linspace

Tạo một mảng có các giá trị phân bố đều trong một khoảng đã cho

In [55]:
arr_lins_ed = np.linspace(0,10,5,retstep =True, endpoint=False)
arr_lins_ed 

(array([0., 2., 4., 6., 8.]), np.float64(2.0))

Hàm np.random.random

Tạo ra giá trih ngãy nhiên trong khoảng từ 0 đến 1

In [56]:
arr_rd = np.random.random(10)
arr_rd

array([0.60285445, 0.66449244, 0.36326651, 0.36811396, 0.84941761,
       0.59209069, 0.61644448, 0.302819  , 0.93580511, 0.8755082 ])

In [59]:
arr_normal = np.random.normal(loc=0.0, scale=1.0, size=20)

arr_normal

array([-0.06795794, -0.62449438, -1.82062666, -1.73890327,  0.23479901,
        0.13962226,  2.05219469, -0.46894562, -0.60321842,  1.1175014 ,
        0.54814145, -0.84524016,  0.38591556,  1.47697587, -0.91563826,
        1.04615716, -0.06938672, -1.2736909 ,  0.28688885,  0.29807488])

In [64]:
arr_int_rd = np.random.randint(
    low=1,      # giá trị nhỏ nhất (bao gồm)
    high=20,    # giá trị lớn nhất (không bao gồm)
    size=6,     # số lượng phần tử muốn tạo
    dtype=np.int32  # kiểu dữ liệu của mảng kết quả
)
arr_int_rd

array([10, 13, 13, 16, 13,  1], dtype=int32)

In [65]:
arr_int_rd = np.random.randint(
    low=1,      # giá trị nhỏ nhất (bao gồm)
    high=20,    # giá trị lớn nhất (không bao gồm)
    size=(3,4),     # số lượng phần tử muốn tạo
    dtype=np.int32  # kiểu dữ liệu của mảng kết quả
)
arr_int_rd

array([[ 2, 17,  5, 13],
       [16, 18, 18,  4],
       [ 9,  5,  9,  8]], dtype=int32)

Hàm np.eye

Tạo ra ma trận đơn vị

In [71]:
arr_eye = np.eye(10)
arr_eye

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

Hàm np.empty

Tạo một mảng ngẫu nhiên hoàn toàn

In [72]:
array_emp = np.empty((3,4))
array_emp

array([[9.85352709e-312, 9.86342650e-312, 9.85352732e-312,
        1.26974871e-321],
       [0.00000000e+000, 4.47032019e-038, 4.51251879e-090,
        3.92320725e+179],
       [4.29341750e-038, 1.40856120e-075, 3.99910963e+252,
        8.34402699e-309]])

## 3.3 XỬ LÝ DỮ LIỆU TRÊN MẢNG CƠ BẢN VỚI NUMPY

In [73]:
arr_test = np.random.randint(1,20,(4,6))
arr_test

array([[ 4, 13, 14,  6, 12, 17],
       [17, 13,  2,  7,  9, 18],
       [ 5,  7, 17, 11, 10,  5],
       [ 2,  4, 19, 10, 11, 12]], dtype=int32)

In [78]:
# kích thước mảng
arr_test.ndim

2

In [75]:
#Tổng số phần tử trong mảng
arr_test.size

24

In [76]:
# Kiểm tra kiểu dưz liệu trong mảng
arr_test.dtype

dtype('int32')

In [ ]:
# Kiểm tra kích thước theo byte mỗi phần tử
arr_test.item

In [80]:
#Kiểm tra tổng kích thước theo byte
arr_test.nbytes

96

In [79]:
arr_test

array([[ 4, 13, 14,  6, 12, 17],
       [17, 13,  2,  7,  9, 18],
       [ 5,  7, 17, 11, 10,  5],
       [ 2,  4, 19, 10, 11, 12]], dtype=int32)

In [82]:
s_0 = np.sum(arr_test, axis = 0) # Vị trí cột 
s_0

array([28, 37, 52, 34, 42, 52])

In [83]:
s_1 = np.sum(arr_test, axis = 1) #      Vị trí hàng
s_1

array([66, 66, 55, 58])

In [84]:
arr

array([1, 2, 3, 4, 5])

In [85]:
arr[0:2]

array([1, 2])

In [86]:
arr_test

array([[ 4, 13, 14,  6, 12, 17],
       [17, 13,  2,  7,  9, 18],
       [ 5,  7, 17, 11, 10,  5],
       [ 2,  4, 19, 10, 11, 12]], dtype=int32)

In [88]:
arr_test[2,0] # Lấy theo hàng

np.int32(17)

In [89]:
arr_test[0,2] # Lấy theo cột


np.int32(14)

In [90]:
arr_test[1,4] # Lấy theo tọa độ

np.int32(9)

In [91]:
arr_test[1, 1:4]  # Lấy các phần tử từ cột 1 đến 3 của hàng thứ 2 trong mảng 2 chiều


array([13,  2,  7], dtype=int32)

In [92]:
arr_list_test = np.random.randint(1,20,10)
arr_list_test

array([11, 13,  1, 11, 17, 15, 14,  8, 13,  6], dtype=int32)

In [93]:
arr_list_test[1:5]

array([13,  1, 11, 17], dtype=int32)

In [94]:
arr_list_test[4:8]

array([17, 15, 14,  8], dtype=int32)

In [95]:
arr_list_test[-4:-1]

array([14,  8, 13], dtype=int32)

In [96]:
arr_list_test[1:8:2]

array([13, 11, 15,  8], dtype=int32)

In [97]:
arr_list_test[::2]

array([11,  1, 17, 14, 13], dtype=int32)

In [98]:
arr_list_test[::-1]

array([ 6, 13,  8, 14, 15, 17, 11,  1, 13, 11], dtype=int32)

In [100]:
arr_test

array([[ 4, 13, 14,  6, 12, 17],
       [17, 13,  2,  7,  9, 18],
       [ 5,  7, 17, 11, 10,  5],
       [ 2,  4, 19, 10, 11, 12]], dtype=int32)

In [101]:
arr_test[1,1:4] # Lấy theo mảng ứng với cột/hàng nào đó

array([13,  2,  7], dtype=int32)

In [102]:
arr_test[0:3,1:4]

array([[13, 14,  6],
       [13,  2,  7],
       [ 7, 17, 11]], dtype=int32)

### Xem và sao chép mảng

Hàm np.view

Tạo ra 

In [103]:
arr_m  = np.array([1,2,3,4,5,6,7,8,9])
arr_m


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
arr_m_reshapw = arr_m.reshape((3,3), order = 'c')
arr_m_reshapw

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [113]:
arr_m_reshape = np.reshape(arr_m, shape = (3,3), order = 'F')
arr_m_reshape

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [115]:
arr_m_reshape_1 = np.reshape(arr_m, shape = (3,3), order = 'C')
arr_m_reshape_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [116]:
arr_x = np.array([1,2,3])

In [117]:
arr_x

array([1, 2, 3])

In [118]:
arr_x.reshape((1,3))

array([[1, 2, 3]])

In [119]:
arr_x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [138]:
arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])

In [122]:
np.concatenate([arr_1,arr_2])

array([1, 2, 3, 4, 5, 6])

In [141]:
arr_1_1 = np.array([[1,2,3],
                 [4,5,6]])
arr_2_1 = np.array([[4,5,6],
                 [7,8,9]])

In [142]:
np.concatenate([arr_1_1,arr_2_1])

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [7, 8, 9]])

In [143]:
np.concatenate([arr_1_1,arr_2_1], axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [7, 8, 9]])

In [144]:
np.concatenate([arr_1_1,arr_2_1], axis = 1)

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8, 9]])

Hàm np.vstack   -   Chồng các mảng theo chiều dọc (axis = 0)

Hàm np.hstack   -   Chồng các mảng theo chiều ngang (axis = 1)

In [145]:
arr_1_1_1 = np.array([[1,2,3],
                 [4,5,6]])
arr_2_1_1 = np.array([[4,5,6],
                 [7,8,9]])

In [146]:
np.vstack([arr_1_1_1, arr_2_1_1])

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [7, 8, 9]])

In [147]:
np.hstack([arr_1_1_1, arr_2_1_1])

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8, 9]])

Hàm np.split()

Hàm cắt mảng

In [ ]:
arr_c = np.arange(20)
arr_c

In [ ]:
result = np.split((arr_c), [0,6])
result

#### ***3.3.5. Thêm, sửa, xóa phần tử trong mảng***

#### **Ví dụ 3.3.5.2: Thêm phần tử vào vị trí cụ thể trong mảng 1 chiều**

In [3]:
import numpy as np

In [4]:
#Thêm phần tử vào vị trí cụ thể trong mảng 1 chiều:
arr = np.array([1, 2, 3, 4, 5]) 
new_element = 10
index_to_insert = 2
new_arr = np.insert(arr, index_to_insert, new_element)
print(new_arr)

[ 1  2 10  3  4  5]


In [5]:
#Thêm phần tử vào vị trí cụ thể trong mảng 2 chiều:
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])
new_element = [7, 8]
row_to_insert = 1
new_arr_2d=np.insert(arr_2d,row_to_insert,new_element,axis=0)
print(new_arr_2d)

[[1 2]
 [7 8]
 [3 4]
 [5 6]]


#### ***3.3.6. Tìm kiếm, sắp xếp mảng.***

### ***a. Tìm kiếm***

#### **Ví dụ 3.3.6.1. Tìm phần tử có giá trị x trong một mảng numpy.**

In [6]:
#Tìm chỉ mục (vị trí) phần tử trong mảng 1 chiều:
arr = np.array([1, 2, 3, 4, 5])
indices = np.where(arr==3)
indices

(array([2]),)

#### **Ví dụ 3.3.6.2.**

In [7]:
arr = np.array([1, 2, 3, 4, 5])
indices = np.argwhere(arr==3)
indices

array([[2]])

#### **Ví dụ 3.3.6.3**

In [8]:
arr = np.array([1, 2, 3, 4, 5])
indices = np.argwhere(arr==3)
indices

array([[2]])

### ***b. Sắp xếp mảng***

#### **Ví dụ 3.3.6.4.**

#### ****Sắp xếp tăng****

In [9]:
arr = np.array([1, 2, 3, 4, 5])
sorted_arr = np.sort(arr)
sorted_arr

array([1, 2, 3, 4, 5])

In [10]:
arr = np.array([1, 2, 3, 4, 5])
arr.sort()
arr

array([1, 2, 3, 4, 5])

#### ****Sắp xếp giảm****

In [12]:
arr = np.array([3, 1, 4, 2, 5])
sorted_arr_descending= np.sort(arr)[::-1]
sorted_arr_descending

array([5, 4, 3, 2, 1])

In [13]:
arr = np.array([3, 1, 4, 2, 5])
arr.sort()
arr[::-1]

array([5, 4, 3, 2, 1])

#### ***3.3.7. Xóa mảng Numpy***

### ***a. Xóa phần tử trong mảng NumPy:***

#### **Ví dụ 3.3.7.1.**

In [14]:
#Xóa một phần tử ở vị trí trong mảng
arr = np.array([3, 1, 4, 2, 5])
idx_to_delete = 2 #Xóa phần tử 4 ở chỉ mục 2.
new_arr=np.delete(arr,idx_to_delete)
new_arr

array([3, 1, 2, 5])

In [15]:
#Xóa nhiểu phần tử trong mảng
arr = np.array([3, 1, 4, 2, 5])
idx_to_delete = [1, 3]
new_arr = np.delete(arr, idx_to_delete)
new_arr

array([3, 4, 5])

In [19]:
#Xóa phần tử trên mảng 2 chiều
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_idx_to_delete = 1
new_arr_2d = np.delete(arr_2d, row_idx_to_delete, axis=0)
new_arr_2d

array([[1, 2, 3],
       [7, 8, 9]])

#### **Ví dụ 3.3.7.2.**

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
del arr
arr

In [22]:
arr = np.array([1, 2, 3, 4, 5])
arr = None
print(arr)

None


#### ***3.3.8. Structured Array và RecordArrays trong NumPy***

### ***a. Mảng cấu trúc - Structure Array***

In [24]:
import numpy as np
# Định nghĩa kiểu dữ liệu cho một Structured Array
dtype = [('name', 'U20'), ('age', int), ('height', float)]
# Tạo một Structured Array
data = np.array([('Minh', 22, 181.3),
('Lan', 40, 160.6),
('Linh', 31, 163.2),
('Lương',18,175.5),
('Thanh',50, 165.0)], dtype=dtype)
print(data)
print(data.dtype)

[('Minh', 22, 181.3) ('Lan', 40, 160.6) ('Linh', 31, 163.2)
 ('Lương', 18, 175.5) ('Thanh', 50, 165. )]
[('name', '<U20'), ('age', '<i8'), ('height', '<f8')]


Khởi tạo Structured Array.

Dictionary

In [28]:
np.dtype({'names':('name','age','height'),
'formats':('U10','i4','f8')})

dtype([('name', '<U10'), ('age', '<i4'), ('height', '<f8')])

list

In [29]:
np.dtype([('name','S10'),('age','i4'),('height','f8')])

dtype([('name', 'S10'), ('age', '<i4'), ('height', '<f8')])

String

In [32]:
np.dtype('S10,i4,f8')

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

#### ***b. Record Arrays:***

In [33]:
import numpy as np
# Định nghĩa kiểu dữ liệu cho một Structured Array
dtype = [('name', 'U20'), ('age', int), ('height', float)]
# Tạo một Structured Array
data = np.array([('Minh', 22, 165.5),
('Lan', 40, 160.0),
('Linh', 31, 165.0),
('Lương',18,166.5),
('Thanh',50, 170.0)], dtype=dtype)
# Truy cập các trường bằng tên
print(data['name']) # In ra mảng 'name'
print(data['age']) # In ra mảng 'age'
print(data['height']) # In ra mảng 'height'

['Minh' 'Lan' 'Linh' 'Lương' 'Thanh']
[22 40 31 18 50]
[165.5 160.  165.  166.5 170. ]


#### ***3.4. TÍNH TOÁN TRÊN MẢNG NUMPY***

### ***3.4.1. Hạn chế của giải thuật vòng lặp***

#### ***Ví dụ 3.4.1. Tạo mảng NumPy với 100 triệu phần tử kiểu int64. Sau đó thực hiện tính tổng các phần tử trong mảng Numpy bằng hai cách:***

In [35]:
import numpy as np
import time
# Tạo một mảng NumPy với 100.000.000 phần tử
arr = np.arange(100000000, dtype=np.int64)
# Tính tổng các phần tử của mảng bằng vòng lặp
start_time = time.time()
total = np.int64(0)
for num in arr:
    total += num
end_time = time.time()
elapsed_time_loop = end_time - start_time
print("Tổng các phần tử mảng arr khi sử dụng vòng lặp:", total)
print("Thời gian (giây) khi sử dụng vòng lặp:", elapsed_time_loop)
# Tính tổng các phần tử của mảng bằng np.sum()
start_time = time.time()
total = np.sum(arr)
end_time = time.time()
elapsed_time_npsum = end_time - start_time
print("Tổng các phần tử mảng arr khi sử dụng hàm np.sum():", total)
print("Thời gian (giây) khi sử dụng np.sum():", elapsed_time_npsum)
num_times_faster = elapsed_time_loop / elapsed_time_npsum
print("Sử dụng vòng lặp chậm hơn: ~",int(num_times_faster),"lần")

Tổng các phần tử mảng arr khi sử dụng vòng lặp: 4999999950000000
Thời gian (giây) khi sử dụng vòng lặp: 26.665302515029907
Tổng các phần tử mảng arr khi sử dụng hàm np.sum(): 4999999950000000
Thời gian (giây) khi sử dụng np.sum(): 0.12578368186950684
Sử dụng vòng lặp chậm hơn: ~ 211 lần


### ***3.4.2. Ưu điểm mảng numpy với list***

In [37]:
import numpy as np
arr1 = np.array([0,1,2])
arr2 = np.array([5,5,5])
arr_sum = arr1 + arr2
arr_sum

array([5, 6, 7])

In [38]:
import numpy as np
arr1 = np.array([0,1,2])
arr1 + 5

array([5, 6, 7])

In [39]:
import numpy as np
arr = np.array([0,1,2])
arr

array([0, 1, 2])

In [40]:
M=np.ones((3,3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
arr + M

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [42]:
import numpy as np
arr1 = np.arange(3)
arr2=np.arange(3)[:,np.newaxis]
print(arr1)
print(arr2)

[0 1 2]
[[0]
 [1]
 [2]]


In [43]:
arr1 + arr2

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [45]:
import numpy as np
arr1=np.ones((2,3))
arr2 = np.arange(3)
print(arr1.shape)
print(arr2.shape)

(2, 3)
(3,)


In [46]:
arr1+arr2

array([[1., 2., 3.],
       [1., 2., 3.]])

In [44]:
import numpy as np
# Tạo mảng dữ liệu với kích thước lớn (1000 phần tử)
data = np.random.randint(100, 200, size=1000)
# Tính toán tỷ lệ phần trăm tăng trưởng của từng phần tử so với giá trị trung bình
mean_value = data.mean()
percentage_growth = (data - mean_value) / mean_value * 100
# In ra 10 phần tử đầu tiên của mảng dữ liệu và tỷ lệ phần trăm tăng trưởng
print("Dữ liệu gốc:", data[:10])
print("Tỷ lệ phần trăm tăng trưởng:",
percentage_growth[:10])

Dữ liệu gốc: [142 180 160 147 176 196 111 108 168 116]
Tỷ lệ phần trăm tăng trưởng: [ -5.04974858  20.35947363   6.98619878  -1.70642987  17.68481866
  31.05809351 -25.7783246  -27.78431582  12.33550872 -22.43500588]


In [47]:
import numpy as np
#Mảng đích để lưu trữ kết quả
output=np.zeros((3,3))
#Mảng nguồn arr1, arr2
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
#Thực hiện phép cộng và lưu trữ kết quả vào mảng đích output
np.add(arr1,arr2, out=output)
#In kết quả
print(output)

[[5. 7. 9.]
 [5. 7. 9.]
 [5. 7. 9.]]


In [48]:
import numpy as np
visitors = np.array([10200, 9875, 13567,7900,11200, 8871, 12567])

In [50]:
sum = 0
for i in visitors:
    if (i>10000):
        sum+=i
print(sum)

47534


In [51]:
mask = visitors > 10000
mask

array([ True, False,  True, False,  True, False,  True])

In [52]:
#Áp dụng mask để lọc các phần tử thỏa mãn điều kiện (>10000)
visitors[mask]

array([10200, 13567, 11200, 12567])

In [53]:
#Tính tổng mảng các phần tử được lọc ra
visitors[mask].sum()

np.int64(47534)

In [54]:
# Tạo mảng ngẫu nhiên
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])
# Toán tử so sánh dạng ufuncs
result1 = arr1 > arr2 # Lớn hơn
result2 = arr1 == arr2 # Bằng nhau
result3 = arr1 <= arr2 # Nhỏ hơn hoặc bằng
print("Kết quả lớn hơn:", result1)
print("Kết quả bằng nhau:", result2)
print("Kết quả nhỏ hơn hoặc bằng:", result3)

Kết quả lớn hơn: [False False False  True  True]
Kết quả bằng nhau: [False False  True False False]
Kết quả nhỏ hơn hoặc bằng: [ True  True  True False False]


In [55]:
import numpy as np
arr = np.array([[1,0,3],
[0,5,0],
[7,0,9]])
count = np.count_nonzero(arr)
count

np.int64(5)

In [61]:
import numpy as np
diemTB = np.array([6.7, 8, 4, 5.8, 9, 8.3, 5, 7.2, 5.5])

In [60]:
diem = np.array([6.7, 8, 4, 5.8, 9, 8.3, 5, 7.2, 5.5])
boolArr=(diemTB >= 8) & (diemTB <= 10)
boolArr

array([False,  True, False, False,  True,  True, False, False, False])

In [63]:
np.count_nonzero(boolArr)

np.int64(3)

In [66]:
np.count_nonzero((diemTB >= 8) & (diemTB <= 10))

np.int64(3)

In [67]:
np.sum(boolArr)

np.int64(3)

In [69]:
import numpy as np
arr = np.array([[1,0,3],
[0,5,0],
[7,0,9]])
#Sử dụng phương thức sum kèm theo tham số axis (trục) tương ứng

print("Số phần tử khác 0 theo mỗi hàng:",np.sum(arr !=0, axis=1))
print("Số phần tử khác 0 theo mỗi cột:",np.sum(arr!=0, axis=0))

Số phần tử khác 0 theo mỗi hàng: [2 1 2]
Số phần tử khác 0 theo mỗi cột: [2 1 2]


In [71]:
print("Trong mảng arr có phần tử > 5: ", np.any(arr > 8))
print("Trong mảng arr có phần tử < 0: ", np.any(arr < 0))
print("Trong mảng arr tất cả các phần tử đều < 10: ", np.all(arr < 10))
print("Trong mảng arr tất cả các phần tử đều = 3:", np.all(arr == 3))

Trong mảng arr có phần tử > 5:  True
Trong mảng arr có phần tử < 0:  False
Trong mảng arr tất cả các phần tử đều < 10:  True
Trong mảng arr tất cả các phần tử đều = 3: False


In [72]:
print("Kiểm tra từng cột trong mảng arr, \ncột nào có tất cả các phần tử lớn hơn 1: \n",
np.all(arr > 1, axis=0))

Kiểm tra từng cột trong mảng arr, 
cột nào có tất cả các phần tử lớn hơn 1: 
 [False False False]


In [73]:
import numpy as np
import numpy.ma as ma
#Tạo một mảng NumPy bình thường
arr = np.array([1,2,3,4,5,6,7,8,9])
# Tạo một mảng mask cho các giá trị không hợp lệ
mask =arr>6
masked_arr=np.ma.masked_array(arr,mask)
masked_arr

masked_array(data=[1, 2, 3, 4, 5, 6, --, --, --],
             mask=[False, False, False, False, False, False,  True,  True,
                    True],
       fill_value=999999)

In [74]:
# Lấy các giá trị hợp lệ từ mảng ban đầu bằng cách sử dụng mảng mask
valid_values = arr[~mask]
print("Dữ liệu ban đầu:", arr)
print("Mảng mask:", mask)
print("Các giá trị hợp lệ từ mảng ban đầu:", valid_values)

Dữ liệu ban đầu: [1 2 3 4 5 6 7 8 9]
Mảng mask: [False False False False False False  True  True  True]
Các giá trị hợp lệ từ mảng ban đầu: [1 2 3 4 5 6]


In [75]:
import numpy as np
import numpy.ma as ma
#Tạo một mảng NumPy bình thường
arr = np.array([1,2,3,4,5,6,7,8,9])
# Tạo một mảng mask cho các giá trị không hợp lệ
mask =arr>6
masked_arr=np.ma.masked_array(arr,mask,fill_value=100)
print("Masked Array chưa được điền: ", masked_arr)
print("Masked Array đã điền: ", masked_arr.filled())

Masked Array chưa được điền:  [1 2 3 4 5 6 -- -- --]
Masked Array đã điền:  [  1   2   3   4   5   6 100 100 100]


In [77]:
arr = np.array([1,2,3,4,5,6,7,8,9])
#loại các giá trị nhỏ hơn 5
masked_arr1=np.ma.masked_less(arr,5)
print("masked_arr1 :",masked_arr1)
#loại các giá trị nhỏ hơn hoặc bằng 5
masked_arr2=np.ma.masked_less_equal(arr,5)
print("masked_arr2 :", masked_arr2)

masked_arr1 : [-- -- -- -- 5 6 7 8 9]
masked_arr2 : [-- -- -- -- -- 6 7 8 9]


In [78]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
#Truy xuất các phần tử bằng một danh sách các chỉ mục
indices = [1, 3, 4]
sub_arr_1 = arr[indices]
print(sub_arr_1)

[20 40 50]


In [79]:
#Fancy indexing và boolean
sub_arr_boolean = arr[arr > 50]
print("Orignial Array:\n",arr)
# Boolean Indexing
print("After Boolean Condition:",arr[arr>50])

Orignial Array:
 [10 20 30 40 50 60 70 80 90]
After Boolean Condition: [60 70 80 90]


In [80]:
#Mảng chỉ mục là mảng 2 chiều
idx_arr=np.array([[1,2],
[5,6]])
sub_arr_2=arr[idx_arr]
print(sub_arr_2)

[[20 30]
 [60 70]]


In [88]:
arr = np.arange(16).reshape(4, 4)
print("Mảng gốc ban đầu:\n arr = ", arr)
#Lấy các phần tử arr[3, 1], arr[3, 2] và arr[3, 3]
sub_arr = arr[3, [1, 2, 3]]
print("Mảng con: sub_arr = ", sub_arr)

Mảng gốc ban đầu:
 arr =  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Mảng con: sub_arr =  [13 14 15]


In [86]:
# Lấy tất cả các phần tử nằm tại hàng >= 1 và các cột = 1, 2, 3 tương ứng
sub_arr = arr[1:, [1, 2, 3]]
print("Mảng con sub_arr:\n", sub_arr)

Mảng con sub_arr:
 [[ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [87]:
#Fancy Indexing và masks
arr=np.array([[1,2,3],
[4,5,6],
[7,8,9]])
masks=arr[0,:]%2 == 0 #Lấy hàng 0, chia các phần tử tương ứng 1,2,3 cho 2,
print("masks:",masks) #Kết quả là mảng [Flase True False]
sub_arr=arr[:,masks] # Kết hợp Fancy indexing và mask, dấu ':' ở vị trí hàng
# cho biết lấy toàn bộ các hàng của mảng,
# chỉ mục cột là masks, chỉ có 1 phần tử True ở vị trí 1
# Vì vậy chỉ lấy cột có chỉ mục 1, tức cột 1
print("Mảng con mới :\n",sub_arr)

masks: [False  True False]
Mảng con mới :
 [[2]
 [5]
 [8]]
