In [1]:
import numpy as np 
import pandas as pd
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

first_diff = ser.diff().dropna() 

second_diff = first_diff.diff().dropna() 

print("Series gốc:")
print(ser.values)
print("\n" + "-"*20 + "\n")
print("1. Hiệu số thứ nhất (First Difference):")
print(first_diff.values)
print("\n" + "-"*20 + "\n")
print("2. Hiệu số thứ cấp (Second Difference):")
print(second_diff.values)

Series gốc:
[ 1  3  6 10 15 21 27 35]

--------------------

1. Hiệu số thứ nhất (First Difference):
[2. 3. 4. 5. 6. 6. 8.]

--------------------

2. Hiệu số thứ cấp (Second Difference):
[1. 1. 1. 1. 0. 2.]
